name: Terraform CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0" # Specify your desired Terraform version here

      - name: Cache Terraform plugins
        uses: actions/cache@v2
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-plugins-${{ runner.os }}-v1

      - name: Validate Terraform code
        run: terraform validate
        continue-on-error: true

      - name: Plan Terraform changes
        run: terraform plan -input=false -lock=false
        continue-on-error: true

      - name: Fail the build if validation or planning failed
        run: |
          if [ ${{ job.status }} == "failure" ]; then
            echo "Terraform validation or planning failed. Exiting with status 1."
            exit 1
          fi
