name: Build.

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code.
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0" # Specify your desired Terraform version here
          
      # Caching Terraform Plugins
      - name: Cache Terraform plugins
        uses: actions/cache@v2
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }

      - name: Validate Terraform code
        run: terraform validate
        continue-on-error: true

      - name: Plan Terraform changes
        run: terraform plan -input=false -lock=false
        continue-on-error: true
