name: build
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  JS-build:
    runs-on: ubuntu-latest
    steps:
      # Check Out Code.
      - uses: actions/checkout@v3

      # Use Node Version 18.x
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Caching npm modules.
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm clean install
        run: npm ci 

      - name: Test
        run: npm test

      - name: Build
        run: npm run build --if-present

  Trivy-Scans:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build -t 'trivy:${{ github.sha }}' .

      - name: Show Images
        run: docker images ls

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'trivy:${{ github.sha }}'
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: 'trivy-results-${{ github.sha }}.sarif'
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-${{ github.sha }}.sarif'

  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output results.sarif || true'
      - name: rename the sarif file.
        run: mv results.sarif 'njss-results-${{ github.sha }}.sarif'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'njss-results-${{ github.sha }}.sarif'

  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Rename the Sarif file.
        run: mv /home/runner/work/github-actions/results/javascript.sarif /home/runner/work/github-actions/results/'CodeQL-{{ github.sha }}.sarif'  
        
      - name: ls
        run: ls -al    

      - name: upload the CodeQL scans to github security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /home/runner/work/github-actions/results/'CodeQL-{{ github.sha }}.sarif' 
