name: "Trivy"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - main
      - releases
      - release/*
      - hotfix/*
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    types:
      - completed

jobs:
  git-sha7:
    name: Determine short git sha
    runs-on: ubuntu-latest
    outputs:
      SHA7: ${{ steps.git-sha7.outputs.value }} # Define the output variable with the name "SHA7"
    steps:
      - name: Resolve git 7-chars sha
        id: git-sha7
        run: |
          echo "::set-output name=value::${GITHUB_SHA::7}"
      - name: Use the output value in the same job
        run: |
          echo "The short git SHA is ${{ steps.git-sha7.outputs.SHA7 }}" # Reference the output value "SHA7" within the same job
