name: Code Style Checks

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:

permissions: read-all

jobs:
  code_style_checks:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Terraform and TFLint
      - name: Setup Terraform and TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.19.0 # Replace this version with the desired TFLint version

      # Step 3: Run TFLint to scan Terraform code
      - name: Run TFLint
        run: tflint -f sarif > tflint_output.sarif

      # Step 4: Format Terraform code using terraform fmt
      - name: Format Terraform code
        run: terraform fmt -recursive -check=true

      # Step 5: Upload TFLint SARIF output to GHAS
      - name: Upload TFLint SARIF output to GHAS
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tflint_output.sarif
