name: Terraform Code Styling Checks

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.9" # Specify your desired Terraform version here

      - name: Cache Terraform plugins
        uses: actions/cache@v2
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
            ${{ runner.os }}-

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate
        continue-on-error: false

      - name: Plan Terraform changes
        run: terraform plan -input=false -lock=false

  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: tfsec-security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true

      - name: Convert tfsec output to SARIF format
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec-results.sarif

      - name: Upload tfsec SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec-results.sarif

  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./  ## replace "./" with the path of Terraform files for scanning.
        continue-on-error: true

      - name: Rename SARIF file
        run: mv results.sarif checkov-results.sarif
        continue-on-error: true

      - name: Upload checkov SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results.sarif
        continue-on-error: true

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint and generate SARIF
        run: tflint -f sarif > tflint-results.sarif
        continue-on-error: true

      - name: Convert to SARIF
        run: |
          echo '{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0-rtm.5.json",
  "runs": [' > terrascan_output.sarif
          cat tflint-results.sarif >> terrascan_output.sarif
          echo ']}' >> terrascan_output.sarif

      - name: Upload TFLint SARIF output to GHAS
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan_output.sarif
