name: TFLint Scan

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:

permissions: read-all

jobs:
  tflint_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform and TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.19.0 # Replace this version with the desired TFLint version

      - name: Run TFLint
        run: tflint --format json > tflint_output.json

      # Convert TFLint output to SARIF format
      - name: Convert TFLint output to SARIF
        uses: tfsec/tfsec-sarif-action@master
        with:
          json_output_path: tflint_output.json
          sarif_output_path: tflint_sarif_output.sarif

      - name: Display SARIF output
        run: cat tflint_sarif_output.sarif

      # You can upload the SARIF output to a security scanning platform or GHAS
      # For GitHub Advanced Security (GHAS) integration, you can use the following step:
      - name: Upload SARIF to GitHub Advanced Security (GHAS)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tflint_sarif_output.sarif
