name: tfsec.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Cache tfsec binary
        id: cache-tfsec
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/tfsec
          key: ${{ runner.os }}-tfsec-${{ hashFiles('tfsec') }}
      - name: Setup tfsec
        run: |
          if ! command -v tfsec &> /dev/null; then
            curl -Lso tfsec https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64
            chmod +x tfsec
            sudo mv tfsec /usr/local/bin/
          fi
      - name: Display tfsec version
        run: tfsec -v

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
