name: tfsec
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install and run tfsec
      - name: Install tfsec
        run: |
          curl -Lso tfsec https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/
          tfsec -v

      # Run tfsec scan and convert to SARIF
      - name: Run tfsec scan and convert to SARIF
        run: |
          tfsec
          tfsec --sarif > tfsec_results.sarif

      # Upload SARIF to GHAS (if desired)
      - name: Upload SARIF to GHAS
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec_results.sarif
